name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create changelog
        id: changelog
        uses: monolith-taehyun/changelog-emitter@v0.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace changelog file
        uses: DamianReeves/write-file-action@master
        with:
          path: CHANGELOG.md
          write-mode: overwrite
          contents: |
            ${{ steps.changelog.outputs.changelog }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
