name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git --no-pager branch
          git remote update
          git fetch --tags
          echo "===="
          git show-ref
          echo "===="
          git checkout main
          ls -al

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Generate Changelog
        run: |
          git --no-pager branch
          git describe --abbrev=0 --tags HEAD^
          ./gradlew generateChangelog

      - name: Commit and Push Changelog
        run: |
          git --no-pager branch
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for release"
          git push origin main